const USER_ACTIONS_TYPES = {
  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",
};
const USERS_ACTIONS_TYPES = {
  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAIL: "GET_USERS_FAIL",
};
// ===============================================================
const PRODUCT_ACTIONS_TYPES = {
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",
};

const PRODUCTS_ACTIONS_TYPES = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAIL: "GET_PRODUCTS_FAIL",
};
// ===============================================================
const SELLER_ACTIONS_TYPES = {
  GET_SELLER: "GET_SELLER",
  GET_SELLER_SUCCESS: "GET_SELLER_SUCCESS",
  GET_SELLER_FAIL: "GET_SELLER_FAIL",
};
const SELLERS_ACTIONS_TYPES = {
  GET_SELLERS: "GET_SELLERS",
  GET_SELLERS_SUCCESS: "GET_SELLERS_SUCCESS",
  GET_SELLERS_FAIL: "GET_SELLERS_FAIL",
};
// ======================================================

const CATEGORIES_ACTIONS_TYPES = {
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",
};
const CATEGORY_ACTIONS_TYPES = {
  GET_CATEGORY: "GET_CATEGORY",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAIL: "GET_CATEGORY_FAIL",
};

export {
  USER_ACTIONS_TYPES,
  USERS_ACTIONS_TYPES,
  PRODUCT_ACTIONS_TYPES,
  PRODUCTS_ACTIONS_TYPES,
  SELLER_ACTIONS_TYPES,
  SELLERS_ACTIONS_TYPES,
  CATEGORIES_ACTIONS_TYPES,
  CATEGORY_ACTIONS_TYPES,
};
